### ISSUE TITLE
 error: this module is not meant to work on Windows

### ISSUE THREAD

**Issue by Mr-x2020** [3v4Si0N/HTTP-revshell#2]
![image](https://user-images.githubusercontent.com/65666323/93309516-23535980-f7f3-11ea-99f5-659d5641cb48.png)

**Comment by 3v4Si0N** [comment]
Noup, you can't execute the .py server on Windows. You have to use the Windows version release  --> https://github.com/3v4Si0N/HTTP-revshell/releases/tag/v1.0
