### ISSUE TITLE
how to use the payload generator

### ISSUE THREAD

**Issue by jepunband** [3v4Si0N/HTTP-revshell#4]
hello, how to use the payload generator to generate on Linux instead on Windows ? So can send the payload manually...

**Comment by JoelGMSec** [comment]
Hi,

Currently the payload generator works only on Windows.
We are already working to make it compatible with Linux, but it is not ready yet.

You have the usage instructions in the README file.


Thanks for using HTTP-revshell!

**Comment by PinkPantherX** [comment]
Does payload generator works on Debian? When I compile payload I can't find it in any folder...
