### ISSUE TITLE
Revshell-Generator.ps1: readip vs ip

### ISSUE THREAD

**Issue by marcos-borges** [3v4Si0N/HTTP-revshell#5]
Revshell-Generator.ps1: On line 147 you define the $readip, but it never get back to $ip, and when the file/payload is created it use $ip, what at that time is the local IP. Basically lines 144-148 is not doing anything.

**Comment by marcos-borges** [comment]
by the way, great script.

**Comment by JoelGMSec** [comment]
Hi!

Thank you for using our tool :)

The issue is already solved, now you can autocomplete the IP by pressing enter or use the IP that you want.


Regards!
